### ISSUE TITLE
DMA - don't get the button "upload to azure migrate"

### ISSUE THREAD

**Issue by anassql** [microsoft/MCW-Line-of-business-application-migration#39]
To assess the on-premises database using Data Migration Assistant we had followed all the steps perfectly but we stopped in point 16 (Ex2-Task4), we did install the DMA and create the assessment but we still don't get the button "upload to azure migrate"

**Comment by jtuliani** [comment]
I investigated this issue. @anassql is absolutely right - the DMA only gives an option to 'Export report', the option to 'Upload to Azure Migrate' (as shown in the screenshot in the lab guide) isn't shown.

Checking the DMA download page (https://www.microsoft.com/en-us/download/details.aspx?id=53595) I notice that a new version of DMA was released on 4/2/2020. The timing would suggest this issue is caused by a change in DMA.

The release notes say this new release includes "Command line support for uploading assessments to Azure Migrate" and "bug fixes to address issues during upload to Azure Migrate". Under existing features, it includes "MA now enables uploading assessments to Azure Migrate service". There's nothing to suggest this was an intentional change.

I strongly suspect this is therefore a DMA bug, that will likely be remedied in future. In the meantime, I suggest leaving the lab guide as-is and just adding a note to the effect:

> **Note:** The DMA may not show the option to upload the assessment to Azure Migrate (known bug). If this happens, simply proceed to the next task.

**Comment by DawnmarieDesJardins** [comment]
@jtuliani @paulopsgility 
Thanks for looking into this for us Jonathan.  If you can please make the note in the guide, I'll merge the change and update the HTML documents.

**Comment by anassql** [comment]
I have the solution: you can uncomment the below line in Dma.exe.config in C:\Program Files\Microsoft Data Migration Assistant path and you should always be able to see “Upload to Azure Migrate” button in case if you run an assessment using Azure SQL DB or Managed Instance as a target server.

**Comment by DawnmarieDesJardins** [comment]
@jtuliani @paulopsgility 
Jonathan/Paul - please review & advise.

**Comment by jtuliani** [comment]
Addressed in #41 - thanks @anassql for the tip, I added a step to update the Dma.exe.config as you described, and tested that it works.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #41

**Comment by sapien47** [comment]
> I have the solution: you can uncomment the below line in Dma.exe.config in C:\Program Files\Microsoft Data Migration Assistant path and you should always be able to see “Upload to Azure Migrate” button in case if you run an assessment using Azure SQL DB or Managed Instance as a target server.

Hello, the problem is back, which line need to be commended  ?

**Comment by DawnmarieDesJardins** [comment]
Reopening issue for further investigation

**Comment by codingbandit** [comment]
@sapien47 - you seem to have missed this step

From within SmartHotelHost, open Windows Explorer and navigate to the C:\Program Files\Microsoft Data Migration Assistant folder. Open the Dma.exe.config file using Notepad. Search for AzureMigrate and remove the  around the line setting the EnableAssessmentUploadToAzureMigrate key. Save the file and close Notepad when done.

![image](https://user-images.githubusercontent.com/3979478/167714808-5a28f73a-f5aa-459e-9d30-a4fe5aef05e2.png)

**Comment by DawnmarieDesJardins** [comment]
Closing issue with clarification note above and merge of PR #96 making instructions clearer.
