### ISSUE TITLE
Data Migration Assistant not displayin the upload to azure migrate button after assessment

### ISSUE THREAD

**Issue by myloking** [microsoft/MCW-Line-of-business-application-migration#42]
After creating the assessment for the SQL database, i can't find the button that says upload assessment to azure migrate

**Comment by paulopsgility** [comment]
Would you please double-check, I don't believe this has changed. The documentation still shows this option as well: https://docs.microsoft.com/en-us/sql/dma/dma-assesssqlonprem?view=sql-server-ver15  

It's possible that either something was changed and the documentation hasnt been updated or something isnt configured correctly.

**Comment by jtuliani** [comment]
This was addressed in PR #41, which was merged just 5 days ago. @myloking, please can you check that you have the latest lab guide? The PR added an additional step to edit the DMA config file after installing but before running the DMA, to enable the 'Upload to Azure Migrate' feature.

**Comment by DawnmarieDesJardins** [comment]
No additional response from myloking, closing as resolved in PR #41

**Comment by DawnmarieDesJardins** [comment]
Reopening due to comment on PR #41 as this is still an issue

**Comment by dwnatwick** [comment]
In reviewing this issue and the previous comments from April 2020.  My recommendation is that if the button does not appear, please wait and refresh to find if it appears.  The comments after going through the modification steps are that it may take a minute for the button to appear.  Thank you very much.

**Comment by DawnmarieDesJardins** [comment]
@clouddude
Hello.  We've reopened and reviewed the original issue.  Can you please let us know if you still do not get the button?  Did you try a refresh?  If you could provide a screenshot that would be helpful.

**Comment by clouddude** [comment]
I will review the next time I deploy. For the current deployment I modified the config file to expose this functionality.

Carsten

On Feb 12, 2021, at 3:26 PM, Dawnmarie DesJardins <notifications@github.com> wrote:

﻿

@clouddude<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fclouddude&data=04%7C01%7C%7C4033db229be64180424808d8cf946d3e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637487583677757653%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FbQVveeWoA7edC2%2FzUD72q5TaZAIVpbXCwfibOP1Gvc%3D&reserved=0>
Hello. We've reopened and reviewed the original issue. Can you please let us know if you still do not get the button? Did you try a refresh? If you could provide a screenshot that would be helpful.

**Comment by DawnmarieDesJardins** [comment]
@clouddude 
Much appreciated Carsten!  We didn't run get this when we tested our fix so any time you can provide screenshots or additional information it's a huge help.  Since you were able to complete the lab, I'm going to close this issue.  If you get it the next time you deploy, please open an issue with what you're seeing.
